### ISSUE TITLE
[all] tracking of ci-workarounds

### ISSUE THREAD

**Issue by chrigl** [kubernetes/cloud-provider-openstack#1871]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

The purpose of this Task is to track workarounds we needed to incorporate to get CI clean

- [ ] #1869 - Disabled Test from cinder-csi-plugin
- [ ] #1888 - Added empty test script to let ci pass
- [ ] #1887 - Disabled Test from manila-csi-plugin
- [ ] conformance tests of cpo (?)
